export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_SHOPS = "SET_SHOPS";
export const SET_ORDERS = "SET_ORDERS";
export const SET_DRIVERS = "SET_DRIVERS";
export const SET_ASSIGNED_ORDERS = "SET_ASSIGNED_ORDERS";
export const SET_ORDER_TO_MODIFY = "SET_ORDER_TO_MODIFY";

export const SET_DRIVER_ORDERS = "SET_DRIVER_ORDERS";

export const SET_LOADING = "SET_LOADING";
